_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.8.8
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.8
            "5": 0.19.4
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
